language: "en-US"

tone_instructions: "Direct, technical. Skip trivial nitpicks, but DO flag pattern deviations, unclear naming, and non-self-explanatory code. Verify library versions before suggesting APIs."

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  sequence_diagrams: true
  poem: false

  path_filters:
    - "!**/*.md"

  path_instructions:
    - path: "apps/backend/api/src/**/*.ts"
      instructions: |
        CRITICAL - VERSION VERIFICATION:
        Before suggesting ANY library usage, verify the exact version in package.json and check current docs. ZERO TOLERANCE for outdated APIs - especially React Hook Form, TanStack Query, zustand, Zod, MUI.
        If unsure, ask rather than suggest deprecated code.

        DIAGRAMS: Create Mermaid diagrams for complex data flow/architecture. One diagram per comment. Ensure valid syntax.

        IGNORE: TODO comments - do not flag them.

        REUSE EXISTING CODE: Before suggesting fixes, search the codebase for existing utilities, helpers, or patterns that solve the same problem. Suggest reusing them instead of writing new code.

        Focus on actual bugs and security issues:
        - SQL injection risks (string concatenation in queries)
        - Missing error handling that could crash the server
        - Authentication/authorization gaps
        - Race conditions that could corrupt data
        - Memory leaks (unclosed connections)
        - Hardcoded secrets/credentials

        Suggest improvements for:
        - N+1 queries (performance impact)
        - Better error messages for debugging

        Skip:
        - Minor style preferences
        - Overly strict type enforcement if types are reasonable

    - path: "apps/frontend/**/*.tsx"
      instructions: |
        CRITICAL - VERSION VERIFICATION:
        Before suggesting ANY library usage, verify the exact version in package.json and check current docs. ZERO TOLERANCE for outdated APIs - especially React Hook Form, TanStack Query, zustand, Zod, MUI.
        If unsure, ask rather than suggest deprecated code.

        DIAGRAMS: Create Mermaid diagrams for complex component interactions/data flow. One diagram per comment. Ensure valid syntax.

        IGNORE: TODO comments - do not flag them.

        REUSE EXISTING CODE: Before suggesting fixes, search the codebase for existing utilities, helpers, or patterns that solve the same problem. Suggest reusing them instead of writing new code.

        Focus on actual bugs:
        - Missing useEffect dependencies causing stale data
        - Infinite render loops
        - Unhandled errors that crash the UI
        - Memory leaks (missing cleanup)
        - XSS vulnerabilities

        Suggest improvements for:
        - Better component patterns if current approach is problematic

        Skip:
        - Formatting and style preferences
        - Overly opinionated component structure suggestions
        - Accessibility suggestions (aria-hidden, aria-label, keyboard navigation, screen readers, focus management)
        - a11y related comments

    - path: "packages/shared/src/**/*.ts"
      instructions: |
        CRITICAL - VERSION VERIFICATION:
        Before suggesting ANY library usage, verify the exact version in package.json and check current docs.
        If unsure, ask rather than suggest deprecated code.

        DIAGRAMS: Create Mermaid diagrams for type relationships/data contracts. One diagram per comment. Ensure valid syntax.

        IGNORE: TODO comments - do not flag them.

        REUSE EXISTING CODE: Before suggesting fixes, search the codebase for existing utilities, helpers, or patterns that solve the same problem. Suggest reusing them instead of writing new code.

        Focus on:
        - Type mismatches that will cause runtime errors
        - Missing null checks where data could actually be null
        - API contract breaking changes

        Skip:
        - Perfect TypeScript purity (some 'any' is pragmatic)
        - Over-engineering simple types

  tools:
    gitleaks:
      enabled: true