openapi: 3.0.0
info:
  title: HuntHub API
  version: 1.0.0
  description: API for managing treasure hunts
paths: {}

components:
  schemas:
    HuntStatus:
      type: string
      enum: [draft, published]
      description: "Hunt status: draft (editable) or published (read-only)"

    Location:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
        radius:
          type: number
      required:
        - lat
        - lng
        - radius

    HuntAccessType:
      type: string
      enum: [creator, viewer, editor]

    ChallengeType:
      type: string
      enum: [clue, quiz, mission, task]

    OptionType:
      type: string
      enum: [choice, input]

    MissionType:
      type: string
      enum: [upload-media, match-location]

    MimeTypes:
      type: string
      enum: [image/jpeg, image/png, image/webp, image/gif, video/mp4, video/webm, audio/mp3, audio/wav, audio/ogg]

    Hunt:
      type: object
      description: "Hunt DTO (merges Hunt master + HuntVersion content for frontend)"
      properties:
        huntId:
          type: integer
          example: 1332
        creatorId:
          type: string
        name:
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/HuntStatus'
        startLocation:
          $ref: '#/components/schemas/Location'
        stepOrder:
          type: array
          description: "Ordered array of step IDs defining step sequence"
          items:
            type: integer
          example: [10, 23, 15]
        steps:
          type: array
          description: "Optional: Full step details (when populated)"
          items:
              $ref: '#/components/schemas/Step'
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - huntId
        - creatorId
        - name
        - status
        - stepOrder

    HuntCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        startLocation:
          $ref: '#/components/schemas/Location'
        steps:
          type: array
          items:
              $ref: '#/components/schemas/StepCreate'
      required:
        - name

    HuntUpdate:
      type: object
      description: Hunt content update (updates draft HuntVersion internally)
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        startLocation:
          $ref: '#/components/schemas/Location'

    Step:
      type: object
      properties:
        stepId:
          type: integer
          example: 10000
        huntId:
          type: integer
          example: 1332
        type:
          $ref: '#/components/schemas/ChallengeType'
        challenge:
          $ref: '#/components/schemas/Challenge'
        requiredLocation:
          $ref: '#/components/schemas/Location'
        hint:
          type: string
        timeLimit:
          type: number
        maxAttempts:
          type: number
        metadata:
          type: object
          additionalProperties: true
          description: Flexible key-value storage for extensibility
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - stepId
        - huntId
        - type
        - challenge

    StepCreate:
      type: object
      description: Step creation (huntId comes from URL parameter)
      properties:
        type:
          $ref: '#/components/schemas/ChallengeType'
        challenge:
          $ref: '#/components/schemas/Challenge'
        requiredLocation:
          $ref: '#/components/schemas/Location'
        hint:
          type: string
        timeLimit:
          type: number
        maxAttempts:
          type: number
      required:
        - type
        - challenge

    StepUpdate:
      type: object
      description: Step update (only editable fields, no id/huntId/timestamps)
      properties:
        type:
          $ref: '#/components/schemas/ChallengeType'
        challenge:
          $ref: '#/components/schemas/Challenge'
        requiredLocation:
          $ref: '#/components/schemas/Location'
        hint:
          type: string
        timeLimit:
          type: number
        maxAttempts:
          type: number
      required:
        - type
        - challenge

    Challenge:
      type: object
      properties:
        clue:
          $ref: '#/components/schemas/Clue'
        quiz:
          $ref: '#/components/schemas/Quiz'
        mission:
          $ref: '#/components/schemas/Mission'
        task:
          $ref: '#/components/schemas/Task'

    Clue:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    Option:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
      required:
        - id
        - text

    QuizValidation:
      type: object
      description: Validation configuration for quiz answers (future feature)
      properties:
        mode:
          type: string
          enum: [exact, fuzzy, contains, numeric-range]
        caseSensitive:
          type: boolean
        range:
          type: object
          properties:
            min:
              type: number
            max:
              type: number
        acceptableAnswers:
          type: array
          items:
            type: string

    Quiz:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        target:
          $ref: '#/components/schemas/Option'
        type:
          $ref: '#/components/schemas/OptionType'
        distractors:
            type: array
            items:
                $ref: '#/components/schemas/Option'
        validation:
          $ref: '#/components/schemas/QuizValidation'
          description: Optional validation rules (future feature)

    Mission:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        referenceAssetIds:
          type: array
          items:
            type: string
          description: Author's reference images/media shown to player
        targetLocation:
          $ref: '#/components/schemas/Location'
        type:
          $ref: '#/components/schemas/MissionType'
        aiInstructions:
          type: string
          description: Instructions for AI to validate player's upload (future feature)
        aiModel:
          type: string
          enum: [gpt-4-vision, claude-vision, gemini-vision]
          description: Which AI model to use for validation (future feature)

    Task:
      type: object
      properties:
        title:
          type: string
        instructions:
          type: string
          description: What the player should do (shown to player)
        aiInstructions:
          type: string
          description: Instructions for AI to validate player's response
        aiModel:
          type: string
          enum: [gpt-4, claude, gemini]
          description: Which AI model to use for validation (future feature)


    User:
      type: object
      properties:
        id:
          type: string
        firebaseUid:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
        profilePicture:
          type: string
        bio:
          type: string
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - id
        - firebaseUid
        - email

    HuntAccess:
      type: object
      properties:
        huntId:
          type: string
        userId:
          type: string
        accessType:
          $ref: '#/components/schemas/HuntAccessType'
        sharedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - huntId
        - userId
        - accessType
        - sharedAt

    AssetUsage:
      type: object
      properties:
        model:
          type: string
        field:
          type: string
        documentId:
          type: string
      required:
        - model
        - field
        - documentId

    StorageLocation:
      type: object
      properties:
        bucket:
          type: string
        path:
          type: string

    Asset:
      type: object
      properties:
        id:
          type: string
        assetId:
          type: integer
          example: 5000
        ownerId:
          type: string
        url:
          type: string
        mimeType:
          $ref: '#/components/schemas/MimeTypes'
        originalFilename:
          type: string
        size:
          type: number
          description: File size in bytes
        thumbnailUrl:
          type: string
        storageLocation:
          $ref: '#/components/schemas/StorageLocation'
        usage:
          type: array
          items:
            $ref: '#/components/schemas/AssetUsage'
          description: Track where this asset is used
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - id
        - assetId
        - ownerId
        - url
        - mimeType

    AssetCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        mime:
          type: string
          minLength: 1
        sizeBytes:
          type: number
          minimum: 1
        url:
          type: string
          minLength: 1
        s3Key:
          type: string
          minLength: 1
      required:
        - name
        - mime
        - sizeBytes
        - url
        - s3Key
