openapi: 3.0.0
info:
  title: HuntHub API
  version: 1.0.0
  description: API for managing treasure hunts
paths: {}

components:
  schemas:
    HuntStatus:
      type: string
      enum: [draft, published, archived]

    Location:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
        radius:
          type: number
      required:
        - lat
        - lng
        - radius

    HuntAccessType:
      type: string
      enum: [creator, viewer, editor]

    ChallengeType:
      type: string
      enum: [clue, quiz, mission, task]

    OptionType:
      type: string
      enum: [choice, input]

    MissionType:
      type: string
      enum: [upload-media, match-location]

    Hunt:
      type: object
      properties:
        id:
          type: string
        creatorId:
          type: string
        name:
          type: string
        description:
          type: string
        currentVersion:
          type: integer
        status:
          $ref: '#/components/schemas/HuntStatus'
        startLocation:
          $ref: '#/components/schemas/Location'
        steps:
          type: array
          items:
              $ref: '#/components/schemas/Step'
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - id
        - creatorId
        - name
        - isPublished
        - currentVersion
        - status

    HuntCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        startLocation:
          $ref: '#/components/schemas/Location'
        steps:
          type: array
          items:
              $ref: '#/components/schemas/StepCreate'
      required:
        - name

    HuntUpdate:
      type: object
      description: Hunt metadata update (steps managed via separate endpoints)
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        startLocation:
          $ref: '#/components/schemas/Location'
      required:
        - name

    Step:
      type: object
      properties:
        id:
          type: string
        huntId:
          type: string
        type:
          $ref: '#/components/schemas/ChallengeType'
        challenge:
          $ref: '#/components/schemas/Challenge'
        requiredLocation:
          $ref: '#/components/schemas/Location'
        hint:
          type: string
        timeLimit:
          type: number
        maxAttempts:
          type: number
        metadata:
          type: object
          additionalProperties: true
          description: Flexible key-value storage for extensibility
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - id
        - challengeType
        - challenge

    StepCreate:
      type: object
      properties:
        huntId:
          type: string
        type:
          $ref: '#/components/schemas/ChallengeType'
        challenge:
          $ref: '#/components/schemas/Challenge'
        requiredLocation:
          $ref: '#/components/schemas/Location'
        hint:
          type: string
        timeLimit:
          type: number
        maxAttempts:
          type: number
      required:
        - challengeType
        - challenge

    Challenge:
      type: object
      properties:
        clue:
          $ref: '#/components/schemas/Clue'
        quiz:
          $ref: '#/components/schemas/Quiz'
        mission:
          $ref: '#/components/schemas/Mission'
        task:
          $ref: '#/components/schemas/Task'

    Clue:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    Option:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
      required:
        - id
        - text

    QuizValidation:
      type: object
      description: Validation configuration for quiz answers (future feature)
      properties:
        mode:
          type: string
          enum: [exact, fuzzy, contains, numeric-range]
        caseSensitive:
          type: boolean
        range:
          type: object
          properties:
            min:
              type: number
            max:
              type: number
        acceptableAnswers:
          type: array
          items:
            type: string

    Quiz:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        target:
          $ref: '#/components/schemas/Option'
        type:
          $ref: '#/components/schemas/OptionType'
        distractors:
            type: array
            items:
                $ref: '#/components/schemas/Option'
        validation:
          $ref: '#/components/schemas/QuizValidation'
          description: Optional validation rules (future feature)

    Mission:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        referenceAssetIds:
          type: array
          items:
            type: string
          description: Author's reference images/media shown to player
        targetLocation:
          $ref: '#/components/schemas/Location'
        type:
          $ref: '#/components/schemas/MissionType'
        aiInstructions:
          type: string
          description: Instructions for AI to validate player's upload (future feature)
        aiModel:
          type: string
          enum: [gpt-4-vision, claude-vision, gemini-vision]
          description: Which AI model to use for validation (future feature)

    Task:
      type: object
      properties:
        title:
          type: string
        instructions:
          type: string
          description: What the player should do (shown to player)
        aiInstructions:
          type: string
          description: Instructions for AI to validate player's response
        aiModel:
          type: string
          enum: [gpt-4, claude, gemini]
          description: Which AI model to use for validation (future feature)


    User:
      type: object
      properties:
        id:
          type: string
        firebaseUid:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
        profilePicture:
          type: string
        bio:
          type: string
        createdAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
        updatedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - id
        - firebaseUid
        - email

    HuntAccess:
      type: object
      properties:
        huntId:
          type: string
        userId:
          type: string
        accessType:
          $ref: '#/components/schemas/HuntAccessType'
        sharedAt:
          type: string
          example: "2024-02-01T10:12:45Z"
          format: date-time
      required:
        - huntId
        - userId
        - accessType
        - sharedAt
